version: '3.8'

services:
  video-downloader:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./downloads:/app/downloads
      - ./audios:/app/audios
      - ./data:/app/data
    environment:
      - NODE_ENV=production
    restart: unless-stopped
